language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
matrix:
  include:
    - python: "2.6"
      dist: trusty
    - python: "3.3"
      dist: trusty
install: true
script: "cd test && python testlex.py && python testyacc.py"
